/*
 * Lone Star Tan — Month-End Inventory Adjustment Form
 * PRODUCT CATALOG (editable data file)
 * ------------------------------------------------------------------
 * This is the seed catalog transcribed from EOM_ADJ_FORM_2026.pdf (~270 SKUs).
 * Corporate refreshes the product mix roughly 1–2x/year. To update the catalog,
 * edit the PRODUCTS array below — no code changes elsewhere are required.
 *
 *   - Add a product:      add a new "..." line, keep alphabetical order.
 *   - Discontinue:        delete the line (or comment it out).
 *   - Watch encoding:     accented names (Crème, Gelée, Minéral, L'obsidienne)
 *                         must be saved as UTF-8.
 *
 * The trailing "OTHER (NAME)" row from the PDF is intentionally NOT included
 * here — write-in products are handled by the form's "Add write-in" feature.
 *
 * STORES (optional): populate to turn the Store Market/Number field into a
 * dropdown. Leave empty to keep it as a free-text input. The store/market list
 * was not in the source PDF — supply the real list here when available.
 */

window.STORE_LIST = [
  // "Market A - 101",
  // "Market A - 102",
  // "Market B - 201",
];

window.PRODUCT_CATALOG = [
  "Abroad",
  "Abroad Packet",
  "AG Soothing Aloe Gel",
  "AG SPF 50 Tattoo Stick",
  "Aloe Mate - Facial Towelette",
  "Amethyst-Facial White Brnz PKT",
  "Amethyst-Facial White Bronzer",
  "Amethyst-Luxe Body Butter",
  "Amethyst-Luxe Body Wash",
  "Amethyst-Luxe Bronzer",
  "Amethyst-Luxe Bronzer PKT",
  "Amethyst-Luxe Intensifier",
  "Amethyst-Luxe Intensifier PKT",
  "Amethyst-Luxe Tan Extender",
  "B.Clean-2oz Hand Sanitizer Gel",
  "Beta-Carotene Infused Drops",
  "BlackLabel-RadiantExtendMousse",
  "BLSunless-BlackIce Moisturizer",
  "BLSunless-Chic CC Face Crème",
  "BLSunless-Flawless Primer",
  "BLSunless-Flawless Primer PKT",
  "BLSunless-IndiGlow Bronze Mist",
  "BLSunless-Indulgent Body Wash",
  "BLSunless-Perfect Bronze Mist",
  "BLSunless-Renewing Body Scrub",
  "BLSunless-Satin Self-Tan Serum",
  "BLSunless-WarmingFaceExfoliant",
  "Bold by G Gentlemen Packet",
  "Breathless",
  "Cal Tan Lip Balm",
  "Candle-PBT LUXE Private Label",
  "Chiseled by G Gentlemen",
  "City Lips Advanced-Clear",
  "City Lips Advanced-LosAngelips",
  "City Lips Advanced-Nude York",
  "City Lips Advanced-Sun Diego",
  "City Lips Advanced-Tinsel Town",
  "City Lips-Advanced Lip Plumper",
  "City Lips-Plumping Day Oil",
  "City Lips-Plumping Lip Oil",
  "Contessa",
  "Contessa Packet",
  "CrystalSunshine-Facial Bronzer",
  "CrystalSunshine-FacialBronzPKT",
  "CrystalSunshine-InShowerExtend",
  "CrystalSunshine-Intensifier",
  "CrystalSunshine-IntensifierPKT",
  "CrystalSunshine-NatBronzer PKT",
  "CrystalSunshine-NaturalBronzer",
  "Cypher Titanium Face Intensifi",
  "Cypher Titanium Intensifier",
  "Cypher Titanium IntensifierPKT",
  "Cypher Titanium Optimizer",
  "Cypher Titanium Optimizer PKT",
  "Cypher Titanium Tan Extender",
  "Dark Desire",
  "Dark Desire Packet",
  "Designer Skin-Glamour Eyes",
  "Diamond Lust-Facial Bronzer",
  "Disposable Thong",
  "Divine",
  "DS FauxNatural-360 SunlessMist",
  "DS FauxNatural-CC Primer",
  "DS FauxNatural-CC Primer PKT",
  "DS FauxNatural-Prep Mitt",
  "DS FauxNatural-Triple Threat",
  "DS FauxNatural-TripleThreatPKT",
  "Eccentric",
  "Eccentric Packet",
  "Electric City",
  "Electric City Packet",
  "Emerald - Body Butter",
  "Emerald - DHA Bronzer",
  "Emerald - DHA Bronzer Packet",
  "Emerald - Facial Bronzer",
  "Emerald - Intensifier",
  "Emerald - Intensifier Packet",
  "Emerald - Luxe Body Wash",
  "Emerald - Tan Extender",
  "Energy Drink-FullThrottle/Mons",
  "Exclusive",
  "Exclusive Packet",
  "Face Mate",
  "Feelin' Beachy",
  "Golden Legacy - Leg Bronzer",
  "Gravitate",
  "Gravitate Packet",
  "Halotherapy-Salt Pod (HaloOne)",
  "Hemp Nation - Original",
  "HN-ArcticBerry&Prosecco Extend",
  "HN-Cocoa Dreams Tan Extender",
  "HN-Pear Blossom&Jasmine Extend",
  "HN-PearBlossom&JasmineBodyWash",
  "HN-SeaSalt+Sandal Body Wash",
  "HN-SeaSalt+Sandalwood Lotion",
  "HN-Sunset Bliss Tan Extender",
  "HN-VanillaBean&PistachBODYWASH",
  "HN-VanillaBean&PistachioExtend",
  "Hot! Black",
  "Intimidation",
  "JWOWW BRONZING Instant Lotion",
  "JWOWW Director's Cut",
  "JWOWW Director's Cut Packet",
  "JWOWW Fit & Flirty",
  "JWOWW Fit & Flirty Packet",
  "JWOWW Hypo DHA Bronzer PKT",
  "JWOWW Hypo Warming Leg Bronzer",
  "JWOWW Hypo White Bronzer",
  "JWOWW Hypo White Bronzer PKT",
  "JWOWW Jersey Heat Tingle",
  "JWOWW Jersey Heat Tingle PKT",
  "Kit-CrystalSun Intensifi Trio",
  "Kit-EmeraldHoliday-BRONZERTrio",
  "Kit-EmeraldHoliday-INTENSFTrio",
  "Kit-L'obsidienneX Face & Body",
  "Kit-Wellness SessionEssentials",
  "LightStim PhotoSerum 1oz",
  "LightStim Sheet Masque-SINGLE",
  "LightStim SheetMasque 6/Box",
  "LightStim-ACNE Handheld",
  "LightStim-PAIN Handheld",
  "LightStim-WRINKLES Handheld",
  "LiLash Eyelash Serum 2mL",
  "Lip Smoothie - Blue Raspberry",
  "Lip Smoothie - Lime",
  "Lip Smoothie Mango - SPF 15",
  "L'OBS Face Intensify Crème PKT",
  "L'OBS Face Intensifying Crème",
  "L'OBS Facial Cleansing Gelée",
  "L'OBS Hyaluronic& Minéral Mist",
  "L'OBS Luxe Body Cleanser",
  "L'OBS Optimizing DHA BronzePKT",
  "L'OBS Optimizing DHA Bronzer",
  "L'OBS Triple Focus Intensifier",
  "L'OBS Triple Focus IntensifPKT",
  "L'OBS Ultra Hydrating Extender",
  "L'obsidienneX-ExosomeAfterSun",
  "L'obsidienneX-ExosomeBODYCrème",
  "L'obsidienneX-ExosomeFaceCrème",
  "L'obsidienneX-Hyaluronic X7",
  "L'obsidienneX-Vitamin C X3",
  "LVX Bronzer",
  "LVX Bronzer Packet",
  "Naturally WOWW Bronzing Drops",
  "No Apologies - Shave Lotion",
  "Oasis Heat",
  "Oasis Heat Packet",
  "Ocean Views",
  "Ocean Views Packet",
  "Packet - Generic",
  "Paradise",
  "Paradise Packet",
  "PBT Gift Card",
  "PBT Hand Sanitizer 2oz-80%",
  "PBT Lotion Bag - free with kit",
  "PBT Premier Applicator Mitt",
  "PBT Premier-Bronzer: AMETHYST",
  "PBT Premier-Bronzer: CITRINE",
  "PBT Premier-Bronzer: GARNET",
  "PBT Premier-Bronzer: IOLITE",
  "PBT Premier-Bronzer: JADE",
  "PBT Premier-Bronzer: ROSE GOLD",
  "PBT Premier-Bronzer: TOPAZ",
  "PBT Premier-Cartridge: DARK",
  "PBT Premier-Cartridge: LIGHT",
  "PBT Premier-Cartridge: MEDIUM",
  "PBT Premier-COLOR STAY",
  "PBT Premier-RAPID ENHANCE",
  "PBT Premier-Scent: BLACK LABEL",
  "PBT Premier-Scent: BREEZE",
  "PBT Premier-Scent: EMERALD",
  "PBT Premier-Scent: PARADISE",
  "PBT Premier-Scent: SERENITY",
  "PBT Premier-Scent: SUNSATIONAL",
  "PBT Premier-Scent:L'OBSIDIENNE",
  "PBT Premier-Scent:MODERN SPORT",
  "PBT Premier-Scent:PEACELOVESUN",
  "PBT SPF Lip Balm - Various",
  "Peepers Eyewear-Modern Colors",
  "Perfect 10 Intensifier",
  "Perfect 10 Natural Bronzer",
  "Red Light Eyewear w/Case",
  "Refined by G Gentleman Tan Extender",
  "RESTORED 2-in-1 Intensifier",
  "RESTORED Moisturizer 16oz",
  "RESTORED Post Cream 4 oz",
  "RESTORED Prep Spray 6 oz",
  "RESTORED RL Prep Towelette",
  "RESTORED Skincare Kit",
  "RESTORED Target Serum 1 oz",
  "RevitaBrow Advanced 3.0ml",
  "RevitaLash Advanced",
  "RevitaLash Advanced 2.0ml MINI",
  "Rooftop Nights",
  "Rooftop Nights Packet",
  "Rugged by G Gentlemen",
  "Sandy Beaches",
  "Scarlet-Tingle Bronzer",
  "Secret Admirer",
  "Secret Admirer Packet",
  "Shea You Love Me (Classic)",
  "Shea You Love Me-Tan Extender",
  "Smart Water - 20 oz",
  "Smooth Faces",
  "Soft Drink - 20 oz",
  "Starlet",
  "Starlet Packet",
  "StickyFeet Disposable Sandals",
  "SYW-Custom Self-Tan Foam",
  "SYW-Custom Self-TanContinuMist",
  "SYW-Enhancing Tan Extender",
  "SYW-Exfoliating Body Scrub",
  "SYW-Gentle Body Wash",
  "SYW-Prime & ColorBalance Mist",
  "Tekton Hybrid Intensifier",
  "Tekton Hybrid Intensifier PKT",
  "Tekton Hybrid Optimizer",
  "Tekton Hybrid Optimizer PKT",
  "Tekton Hybrid Peptide Serum",
  "Total RX - Relief Gel",
  "Twilight Teeth Refill",
  "Twilight Teeth Twi-Light Kit",
  "Vintage Gold (Classic)",
  "Visionary",
  "Visionary Packet",
  "Vital Intensifier",
  "Vital Intensifier Packet",
  "Vital White DHA Bronzer",
  "Vital White DHA Bronzer Packet",
  "Vitamin Water",
  "Water 16 oz. Premier",
  "WW-PBT Keto Boost (60 Ct)",
  "WW-PBT Pure Collagen (60 Ct)",
  "WW-PBT Slim Down Reset (60 Ct)",
  "WW-PBT Stress Relief (60 Ct)",
  "WW-PBT Vitamin D3+K2 (30 Ct)",
  "X-FORTIFY Daily Sustain Mist",
  "X-FORTIFY Red Light LED Brush",
  "X-FORTIFY Stimulating Serum",
];
